bucket=mikegyver99-aws-rag-basic-terraform-state-<ACCOUNT>-us-east-1
key=aws-rag-basic/dev/terraform.tfstate
region=us-east-1
dynamodb_table=mikegyver99-aws-rag-basic-terraform-lock-<ACCOUNT>-us-east-1
