bucket=mikegyver99-aws-rag-basic-terraform-state-<ACCOUNT>-us-west-2
key=aws-rag-basic/dev/terraform.tfstate
region=us-west-2
dynamodb_table=mikegyver99-aws-rag-basic-terraform-lock-<ACCOUNT>-us-west-2
